project_name: terraform-atlantis-config
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: "-X main.VERSION={{.Version}} -s"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
